# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=30)),
                ('volume', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
        ),
    ]
